# Generated by Django 5.2.10 on 2026-02-10 20:57

import core.services.file_service
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='VenueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('is_main', models.BooleanField(default=False)),
                ('country', models.CharField(choices=[('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Spain', 'Spain'), ('United Kingdom', 'United Kingdom'), ('Netherlands', 'Netherlands'), ('Belgium', 'Belgium'), ('Sweden', 'Sweden'), ('Norway', 'Norway'), ('Denmark', 'Denmark'), ('Finland', 'Finland'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('Greece', 'Greece'), ('Turkey (European part)', 'Turkey (European part)'), ('Ireland', 'Ireland'), ('Switzerland', 'Switzerland'), ('Austria', 'Austria'), ('Czech Republic', 'Czech Republic'), ('Slovakia', 'Slovakia'), ('Hungary', 'Hungary'), ('Romania', 'Romania'), ('Bulgaria', 'Bulgaria'), ('Croatia', 'Croatia'), ('Slovenia', 'Slovenia'), ('Lithuania', 'Lithuania'), ('Latvia', 'Latvia'), ('Estonia', 'Estonia'), ('Iceland', 'Iceland'), ('Malta', 'Malta'), ('Luxembourg', 'Luxembourg'), ('Monaco', 'Monaco'), ('Liechtenstein', 'Liechtenstein'), ('Andorra', 'Andorra'), ('San Marino', 'San Marino'), ('USA', 'USA'), ('Japan', 'Japan'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('UK', 'UK'), ('Turkey', 'Turkey'), ('Brazil', 'Brazil'), ('Argentina', 'Argentina'), ('Mexico', 'Mexico'), ('South Africa', 'South Africa'), ('Egypt', 'Egypt'), ('Morocco', 'Morocco'), ('Thailand', 'Thailand'), ('Indonesia', 'Indonesia'), ('Philippines', 'Philippines'), ('Saudi Arabia', 'Saudi Arabia'), ('UAE', 'UAE'), ('Singapore', 'Singapore'), ('South Korea', 'South Korea'), ('Malaysia', 'Malaysia'), ('New Zealand', 'New Zealand')], default='G', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=core.services.file_service.upload_venue_photo)),
                ('opening_hours', models.JSONField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, null=True)),
                ('average_check', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.FloatField(default=0)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('views', models.PositiveIntegerField(default=0)),
                ('daily_views', models.PositiveIntegerField(default=0)),
                ('weekly_views', models.PositiveIntegerField(default=0)),
                ('monthly_views', models.PositiveIntegerField(default=0)),
                ('edit_attempts', models.PositiveIntegerField(default=0)),
                ('last_exchange_update', models.DateField(blank=True, null=True)),
                ('venue_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'venue',
            },
        ),
        migrations.CreateModel(
            name='TableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='venue.venuemodel')),
            ],
            options={
                'unique_together': {('venue', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VenuePhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=core.services.file_service.upload_venue_photo)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='venue.venuemodel')),
            ],
            options={
                'db_table': 'venue_photos',
            },
        ),
        migrations.CreateModel(
            name='TableBookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_datetime', models.DateTimeField()),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=7200))),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table_booking', to='orders.ordermodel')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='venue.tablemodel')),
            ],
            options={
                'db_table': 'table_bookings',
                'indexes': [models.Index(fields=['table', 'booking_datetime'], name='table_booki_table_i_78c88a_idx')],
            },
        ),
        migrations.CreateModel(
            name='VenueTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.tagmodel')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.venuemodel')),
            ],
            options={
                'db_table': 'venue_tags',
                'unique_together': {('venue', 'tag')},
            },
        ),
    ]
