# Generated by Django 5.2.10 on 2026-02-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_alter_tablebookingmodel_time_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuemodel',
            name='country',
            field=models.CharField(choices=[('Andorra', 'Andorra'), ('Argentina', 'Argentina'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Belgium', 'Belgium'), ('Brazil', 'Brazil'), ('Bulgaria', 'Bulgaria'), ('Canada', 'Canada'), ('Croatia', 'Croatia'), ('Czech Republic', 'Czech Republic'), ('Denmark', 'Denmark'), ('Egypt', 'Egypt'), ('Estonia', 'Estonia'), ('Finland', 'Finland'), ('France', 'France'), ('Germany', 'Germany'), ('Greece', 'Greece'), ('Hungary', 'Hungary'), ('Iceland', 'Iceland'), ('Indonesia', 'Indonesia'), ('Ireland', 'Ireland'), ('Italy', 'Italy'), ('Japan', 'Japan'), ('Latvia', 'Latvia'), ('Liechtenstein', 'Liechtenstein'), ('Lithuania', 'Lithuania'), ('Luxembourg', 'Luxembourg'), ('Malaysia', 'Malaysia'), ('Malta', 'Malta'), ('Mexico', 'Mexico'), ('Monaco', 'Monaco'), ('Netherlands', 'Netherlands'), ('New Zealand', 'New Zealand'), ('Norway', 'Norway'), ('Philippines', 'Philippines'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('Romania', 'Romania'), ('San Marino', 'San Marino'), ('Saudi Arabia', 'Saudi Arabia'), ('Singapore', 'Singapore'), ('Slovakia', 'Slovakia'), ('Slovenia', 'Slovenia'), ('South Africa', 'South Africa'), ('South Korea', 'South Korea'), ('Spain', 'Spain'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Thailand', 'Thailand'), ('Turkey', 'Turkey'), ('Turkey (European part)', 'Turkey (European part)'), ('UAE', 'UAE'), ('United Kingdom', 'United Kingdom'), ('USA', 'USA')], default='A', max_length=50),
        ),
    ]
