# Generated by Django 5.2.10 on 2026-02-25 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('venue', '0004_alter_venuemodel_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebookingmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_bookings', to='orders.ordermodel'),
        ),
    ]
