# Generated by Django 5.2.10 on 2026-02-25 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_alter_tablebookingmodel_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tablemodel',
            table='tables',
        ),
    ]
