# Generated by Django 5.2.10 on 2026-02-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0006_alter_tablemodel_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tablemodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tablemodel',
            name='name',
        ),
    ]
