# Generated by Django 5.2.10 on 2026-02-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0007_alter_tablemodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuemodel',
            name='background_tables',
            field=models.ImageField(blank=True, null=True, upload_to='venues/background_tables/'),
        ),
    ]
