# Generated by Django 5.2.10 on 2026-02-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0008_venuemodel_background_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuemodel',
            name='background_tables',
            field=models.URLField(blank=True, null=True),
        ),
    ]
