# Generated by Django 5.2.10 on 2026-03-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0009_alter_venuemodel_background_tables'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VenueTag',
            new_name='VenueTagModel',
        ),
    ]
