# Generated by Django 5.2.10 on 2026-03-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0010_rename_venuetag_venuetagmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuemodel',
            name='currency',
            field=models.CharField(choices=[('UAH', 'Hryvnia'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='UAH', max_length=3),
        ),
    ]
