# Generated by Django 5.2.10 on 2026-03-05 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0011_venuemodel_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableBookingModel',
        ),
    ]
