# Generated by Django 5.2.10 on 2026-04-08 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0012_delete_tablebookingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_logs', to='venue.venuemodel')),
            ],
            options={
                'verbose_name': 'Venue Traffic',
                'verbose_name_plural': 'Venue Traffic',
                'db_table': 'venue_traffic',
                'indexes': [models.Index(fields=['venue', 'timestamp'], name='venue_traff_venue_i_912a67_idx')],
            },
        ),
    ]
