CITIES_BY_COUNTRY = {
    'Andorra': ['Andorra la Vella', 'Arinsal', 'Canillo', 'Encamp', 'Escaldes-Engordany', 'La Massana', 'Ordino', 'Pas de la Casa', 'Sant Julià de Lòria', 'Soldeu'],
    'Argentina': ['Acapulco', 'Buenos Aires', 'Córdoba', 'La Plata', 'Mar del Plata', 'Mendoza', 'Rosario', 'Salta', 'San Miguel', 'Tucumán'],
    'Australia': ['Adelaide', 'Brisbane', 'Canberra', 'Gold Coast', 'Hobart', 'Melbourne', 'Newcastle', 'Perth', 'Sydney', 'Wollongong'],
    'Austria': ['Graz', 'Innsbruck', 'Klagenfurt', 'Linz', 'Salzburg', 'Sankt Pölten', 'Villach', 'Vienna', 'Wels', 'Zell am See'],
    'Bali': ['Denpasar', 'Singaraja', 'Kuta', 'Ubud', 'Sanur', 'Seminyak', 'Canggu', 'Nusa Dua', 'Jimbaran'],
    'Belgium': ['Antwerp', 'Basel', 'Bruges', 'Brussels', 'Charleroi', 'Clervaux', 'Diekirch', 'Esch-sur-Alzette', 'Ghent', 'Leuven', 'Liège', 'Mechelen', 'Mons', 'Namur'],
    'Brazil': ['Belo Horizonte', 'Brasília', 'Curitiba', 'Fortaleza', 'Manaus', 'Porto Alegre', 'Recife', 'Rio de Janeiro', 'Salvador', 'São Paulo'],
    'Bulgaria': ['Burgas', 'Dobrich', 'Plovdiv', 'Pleven', 'Ruse', 'Shumen', 'Sofia', 'Sliven', 'Stara Zagora', 'Varna'],
    'Canada': ['Calgary', 'Edmonton', 'Halifax', 'Hamilton', 'Montreal', 'Ottawa', 'Quebec City', 'Toronto', 'Vancouver', 'Winnipeg'],
    'Croatia': ['Dubrovnik', 'Osijek', 'Pula', 'Rijeka', 'Slavonski Brod', 'Split', 'Šibenik', 'Varaždin', 'Zadar', 'Zagreb'],
    'Czech Republic': ['Brno', 'Hradec Králové', 'Liberec', 'Olomouc', 'Ostrava', 'Pardubice', 'Plzen', 'Prague', 'Ústí nad Labem', 'Zlín'],
    'Denmark': ['Aalborg', 'Aarhus', 'Copenhagen', 'Esbjerg', 'Horsens', 'Kolding', 'Odense', 'Randers', 'Roskilde', 'Vejle'],
    'Egypt': ['Alexandria', 'Aswan', 'Cairo', 'Giza', 'Hurghada', 'Ismailia', 'Luxor', 'Sharm El-Sheikh', 'Suez', 'Tanta'],
    'Estonia': ['Kohtla-Järve', 'Kuressaare', 'Maardu', 'Narva', 'Pärnu', 'Rakvere', 'Sillamäe', 'Tallinn', 'Tartu', 'Viljandi'],
    'Finland': ['Espoo', 'Helsinki', 'Jyväskylä', 'Kuopio', 'Lahti', 'Oulu', 'Pori', 'Tampere', 'Turku', 'Vantaa'],
    'France': ['Bordeaux', 'Lille', 'Lyon', 'Marseille', 'Montpellier', 'Nantes', 'Nice', 'Paris', 'Strasbourg', 'Toulouse'],
    'Germany': ['Berlin', 'Bremen', 'Cologne', 'Dresden', 'Düsseldorf', 'Frankfurt', 'Hamburg', 'Leipzig', 'Munich', 'Stuttgart'],
    'Greece': ['Athens', 'Chania', 'Heraklion', 'Ioannina', 'Kalamata', 'Larissa', 'Patras', 'Rhodes', 'Thessaloniki', 'Volos'],
    'Hungary': ['Budapest', 'Debrecen', 'Győr', 'Kecskemét', 'Miskolc', 'Nyíregyháza', 'Pécs', 'Szeged', 'Székesfehérvár', 'Szombathely'],
    'Iceland': ['Akureyri', 'Akranes', 'Garðabær', 'Hafnarfjörður', 'Hveragerði', 'Mosfellsbær', 'Reykjanesbær', 'Reykjavik', 'Selfoss', 'Stykkishólmur'],
    'Indonesia': ['Bali', 'Bandung', 'Jakarta', 'Makassar', 'Malang', 'Medan', 'Palembang', 'Semarang', 'Surabaya', 'Yogyakarta'],
    'Ireland': ['Athlone', 'Cork', 'Dublin', 'Galway', 'Kilkenny', 'Killarney', 'Limerick', 'Sligo', 'Tralee', 'Waterford'],
    'Italy': ['Bologna', 'Florence', 'Genoa', 'Milan', 'Naples', 'Palermo', 'Rome', 'Turin', 'Venice', 'Verona'],
    'Japan': ['Fukuoka', 'Hiroshima', 'Kobe', 'Kyoto', 'Nagoya', 'Osaka', 'Sendai', 'Sapporo', 'Tokyo', 'Yokohama'],
    'Latvia': ['Daugavpils', 'Jelgava', 'Jēkabpils', 'Jūrmala', 'Liepāja', 'Ogre', 'Rēzekne', 'Riga', 'Valmiera', 'Ventspils'],
    'Liechtenstein': ['Balzers', 'Eschen', 'Gamprin', 'Mauren', 'Planken', 'Ruggell', 'Schellenberg', 'Schaan', 'Triesen', 'Vaduz'],
    'Lithuania': ['Alytus', 'Jonava', 'Kaunas', 'Klaipėda', 'Marijampolė', 'Mažeikiai', 'Panevėžys', 'Šiauliai', 'Utena', 'Vilnius'],
    'Luxembourg': ['Clervaux', 'Diekirch', 'Dudelange', 'Differdange', 'Esch-sur-Alzette', 'Ettelbruck', 'Grevenmacher', 'Luxembourg City', 'Remich', 'Wiltz'],
    'Malaysia': ['George Town', 'Ipoh', 'Johor Bahru', 'Kota Kinabalu', 'Kuching', 'Kuala Lumpur', 'Malacca', 'Petaling Jaya', 'Seremban', 'Shah Alam'],
    'Malta': ['Birkirkara', 'Gozo', 'Mdina', 'Mellieħa', 'Mosta', 'Qormi', 'Sliema', 'St. Julian’s', 'Valletta'],
    'Mexico': ['Acapulco', 'Cancún', 'Guadalajara', 'León', 'Mexico City', 'Mérida', 'Monterrey', 'Puebla', 'Querétaro', 'Tijuana'],
    'Monaco': ['Fontvieille', 'Jardin Exotique', 'La Condamine', 'La Rousse', 'Larvotto', 'Monaco', 'Moneghetti', 'Monte Carlo', 'Les Révoires', 'Saint Roman'],
    'Netherlands': ['Amsterdam', 'Delft', 'Eindhoven', 'Groningen', 'Leiden', 'Maastricht', 'Nijmegen', 'Rotterdam', 'The Hague', 'Utrecht'],
    'New Zealand': ['Auckland', 'Christchurch', 'Dunedin', 'Hamilton', 'Invercargill', 'Napier', 'Palmerston North', 'Rotorua', 'Tauranga', 'Wellington'],
    'Norway': ['Bergen', 'Bodø', 'Drammen', 'Fredrikstad', 'Kristiansand', 'Nordre', 'Oslo', 'Skien', 'Stavanger', 'Trondheim', 'Tromsø'],
    'Philippines': ['Baguio', 'Cagayan de Oro', 'Cebu', 'Davao', 'Iloilo', 'Makati', 'Manila', 'Quezon City', 'Taguig', 'Zamboanga'],
    'Poland': ['Bydgoszcz', 'Gdansk', 'Katowice', 'Krakow', 'Lodz', 'Lublin', 'Niedzica', 'Nitra', 'Poznan', 'Szczecin', 'Wroclaw', 'Warsaw'],
    'Portugal': ['Aveiro', 'Braga', 'Coimbra', 'Évora', 'Faro', 'Funchal', 'Guimarães', 'Lisbon', 'Porto', 'Setúbal'],
    'Romania': ['Brașov', 'Bucharest', 'Cluj-Napoca', 'Constanța', 'Craiova', 'Galați', 'Iași', 'Oradea', 'Ploiești', 'Timișoara'],
    'San Marino': ['Acquaviva', 'Borgo Maggiore', 'Cailungo', 'Chiesanuova', 'Domagnano', 'Faetano', 'Fiorentino', 'Montegiardino', 'San Marino', 'Serravalle'],
    'Saudi Arabia': ['Abha', 'Dammam', 'Hail', 'Jeddah', 'Mecca', 'Medina', 'Riyadh', 'Tabuk', 'Ta’if', 'Khobar'],
    'Singapore': ['Singapore'],
    'Slovakia': ['Banská Bystrica', 'Bratislava', 'Košice', 'Martin', 'Nitra', 'Poprad', 'Prešov', 'Trnava', 'Trenčín', 'Žilina'],
    'Slovenia': ['Celje', 'Kamnik', 'Koper', 'Kranj', 'Ljubljana', 'Maribor', 'Novo Mesto', 'Ptuj', 'Trbovlje', 'Velenje'],
    'South Africa': ['Bloemfontein', 'Cape Town', 'Durban', 'East London', 'Johannesburg', 'Kimberley', 'Nelspruit', 'Port Elizabeth', 'Pretoria', 'Pietermaritzburg'],
    'South Korea': ['Busan', 'Changwon', 'Daegu', 'Daejeon', 'Gwangju', 'Incheon', 'Jeonju', 'Seoul', 'Suwon', 'Ulsan'],
    'Spain': ['Alicante', 'Barcelona', 'Bilbao', 'Ibiza', 'Madrid', 'Malaga', 'Palma', 'Seville', 'Toledo', 'Valencia', 'Zaragoza'],
    'Sweden': ['Gothenburg', 'Helsingborg', 'Jönköping', 'Linköping', 'Malmö', 'Norrköping', 'Stockholm', 'Uppsala', 'Västerås', 'Örebro'],
    'Switzerland': ['Basel', 'Bern', 'Lausanne', 'Lucerne', 'Lugano', 'St. Gallen', 'Thun', 'Zurich'],
    'Thailand': ['Ayutthaya', 'Bangkok', 'Chiang Mai', 'Hat Yai', 'Hua Hin', 'Kanchanaburi', 'Krabi', 'Pattaya', 'Phuket', 'Sukhothai'],
    'Turkey': ['Adana', 'Ankara', 'Antalya', 'Bursa', 'Gaziantep', 'Istanbul', 'Izmir', 'Kayseri', 'Konya', 'Mersin'],
    'Turkey (European part)': ['Bursa', 'Çanakkale', 'Edirne', 'Esenyurt', 'Istanbul', 'Kadıköy', 'Pendik', 'Sarıyer', 'Tekirdağ', 'Üsküdar'],
    'UAE': ['Abu Dhabi', 'Ajman', 'Al Ain', 'Dibba', 'Dubai', 'Fujairah', 'Khor Fakkan', 'Ras Al Khaimah', 'Sharjah', 'Umm Al Quwain'],
    'United Kingdom': ['Birmingham', 'Bristol', 'Cardiff', 'Edinburgh', 'Glasgow', 'Leeds', 'Liverpool', 'London', 'Manchester', 'Sheffield'],
    'USA': ['Atlanta', 'Boston', 'Chicago', 'Dallas', 'Houston', 'Los Angeles', 'Miami', 'New York', 'San Francisco', 'Seattle'],
}

COUNTRIES = list(CITIES_BY_COUNTRY.keys())
