# Generated by Django 5.2.10 on 2026-03-03 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('travel_logistics', '0002_travellogisticsmodel_currency_extraservicemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderextraservicemodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_logistics.extraservicemodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='currency',
            field=models.CharField(choices=[('UAH', 'Hryvnia'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='UAH', max_length=3),
        ),
        migrations.DeleteModel(
            name='ExtraServiceModel',
        ),
    ]
