# Generated by Django 5.2.10 on 2026-03-05 15:39

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderextraservicemodel_service_and_more'),
        ('venue', '0012_delete_tablebookingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderextraservicemodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='travel_calculation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderextraservicemodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_services', to='orders.ordermodel'),
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.ordermodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('HOLD', 'Hold'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='TableBookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('HOLD', 'Hold'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_bookings', to='orders.ordermodel')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='venue.tablemodel')),
            ],
            options={
                'db_table': 'table_bookings',
                'ordering': ['time_range'],
                'indexes': [django.contrib.postgres.indexes.GistIndex(fields=['table', 'time_range'], name='table_booki_table_i_b4e7e5_gist')],
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_active', True)), expressions=[('table', '='), ('time_range', '&&')], name='prevent_overlapping_bookings')],
            },
        ),
    ]
