# Generated by Django 5.2.10 on 2026-03-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderextraservicemodel_price_ordermodel_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('0-1000', '0-1000'), ('1000-3000', '1000-3000'), ('3000-5000', '3000-5000'), ('5000+', '5000+')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='gender_preference',
            field=models.CharField(choices=[('ANY', 'Any'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='ANY', max_length=10),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='payment_type',
            field=models.CharField(choices=[('Each pays for themselves', 'Each pays for themselves'), ('I pay', 'I pay'), ('Someone else pays', 'Someone else pays')], default='Each pays for themselves', max_length=50),
        ),
    ]
