# Generated by Django 5.2.10 on 2026-03-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordermodel_budget_range_ordermodel_gender_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='venue_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='venue_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
