# Generated by Django 5.2.10 on 2026-03-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_ordermodel_venue_latitude_ordermodel_venue_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='services_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
