# Generated by Django 5.2.10 on 2026-02-10 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='venue.venuemodel'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.menumodel'),
        ),
    ]
