# Generated by Django 5.2.10 on 2026-02-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('main', 'Main'), ('dessert', 'Dessert'), ('drink', 'Drink'), ('salad', 'Salad'), ('soup', 'Soup')], default='main', max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='currency',
            field=models.CharField(choices=[('UAH', 'Гривня'), ('USD', 'Долар'), ('EUR', 'Євро')], default='UAH', max_length=3),
        ),
    ]
