# Generated by Django 5.2.10 on 2026-03-02 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_category_alter_menuitem_currency'),
        ('venue', '0009_alter_venuemodel_background_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='currency',
            field=models.CharField(choices=[('UAH', 'Hryvnia'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='UAH', max_length=3),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.menumodel'),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='venue.venuemodel'),
        ),
    ]
