# Generated by Django 5.2.10 on 2026-03-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menumodel_is_published_alter_menuitem_currency_and_more'),
        ('orders', '0003_alter_orderextraservicemodel_service_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItem',
            new_name='MenuItemModel',
        ),
    ]
