# Generated by Django 5.2.10 on 2026-03-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_menuitem_menuitemmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemmodel',
            name='currency',
            field=models.CharField(choices=[('UAH', 'Hryvnia'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='UAH', editable=False, max_length=3),
        ),
    ]
