# Generated by Django 5.2.10 on 2026-03-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menuitemmodel_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemmodel',
            name='category',
            field=models.CharField(choices=[('mains', 'Mains'), ('desserts', 'Desserts'), ('drinks', 'Drinks'), ('salads', 'Salads'), ('soups', 'Soups')], default='mains', max_length=20),
        ),
    ]
