# Generated by Django 5.2.10 on 2026-04-12 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menuitemmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Price cannot be negative.')]),
        ),
    ]
