# Generated by Django 5.2.10 on 2026-02-28 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
        ('venue', '0009_alter_venuemodel_background_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='photo',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('promotion', 'Promotion'), ('event', 'Event')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='venue.venuemodel'),
        ),
        migrations.CreateModel(
            name='NewsImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venue_news/')),
                ('is_cover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.newsmodel')),
            ],
            options={
                'db_table': 'venue_news_images',
                'ordering': ['-created_at'],
            },
        ),
    ]
