# Generated by Django 5.2.10 on 2026-03-28 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordermodel_services_total'),
        ('reviews_feedback', '0001_initial'),
        ('venue', '0012_delete_tablebookingmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate'), ('birthday', 'Birthday'), ('date', 'Date'), ('party', 'Party'), ('meeting', 'Business Meeting'), ('general', 'General')], default='general', max_length=50)),
                ('is_staff_top', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'favorite_collections',
            },
        ),
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'review_likes',
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Spam', 'Spam'), ('Fake', 'Fake'), ('Abuse', 'Abuse'), ('Other', 'Other')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'review_reports',
            },
        ),
        migrations.AlterUniqueTogether(
            name='reviewmodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favoritevenue',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='orders.ordermodel'),
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='owner_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AddConstraint(
            model_name='reviewmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('user', 'order'), name='unique_review_per_order'),
        ),
        migrations.AddField(
            model_name='favoritecollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favoritevenue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favoritevenue',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reviews_feedback.favoritecollection'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritevenue',
            unique_together={('user', 'venue', 'collection')},
        ),
        migrations.AddField(
            model_name='reviewlike',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='reviews_feedback.reviewmodel'),
        ),
        migrations.AddField(
            model_name='reviewlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews_feedback.reviewmodel'),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favoritecollection',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewlike',
            unique_together={('user', 'review')},
        ),
    ]
