# Generated by Django 5.2.10 on 2026-03-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_feedback', '0002_favoritecollection_reviewlike_reviewreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritecollection',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
