export const dynamic = "force-dynamic";
import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { Playfair_Display, Imperial_Script, Roboto } from "next/font/google";

const playfair = Playfair_Display({
  subsets: ["latin", "cyrillic"],
  weight: ["600", "700"],
  style: ["italic"],
  variable: "--font-playfair",
  display: "swap",
});

const imperialScript = Imperial_Script({
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal"],
  variable: "--font-imperial",
  display: "swap",
});

const roboto = Roboto({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "700"],
  style: ["normal"],
  variable: "--font-roboto",
  display: "swap",
});

export const metadata: Metadata = {
  title: "VIP Boozer — Premium Places",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/favicon/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon/favicon-16x16.png", sizes: "16x16", type: "image/png" },
    ],
    apple: "/favicon/apple-touch-icon.png",
  },
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="en" suppressHydrationWarning>
        <body className={`${playfair.variable} ${imperialScript.variable} ${roboto.variable}`}>
          <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
