# Generated by Django 5.2.10 on 2026-02-01 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodel_auth_provider_usermodel_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in format +xx (xxx) xxx-xx-xx', regex='^\\+(\\d{2}) \\(\\d{3}\\) \\d{3}-\\d{2}-\\d{2}$')]),
        ),
    ]
