# Generated by Django 5.2.10 on 2026-02-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profilemodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
            preserve_default=False,
        ),
    ]
