# Generated by Django 5.2.10 on 2026-03-02 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venue', '0009_alter_venuemodel_background_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('iata_code', models.CharField(max_length=3, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
                'db_table': 'airports',
            },
        ),
        migrations.CreateModel(
            name='TravelLogisticsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_type', models.CharField(choices=[('to_airport', 'Transfer to airport'), ('flight', 'Flight'), ('from_airport', 'Transfer from airport')], default='to_airport', max_length=20)),
                ('price_per_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_logistics', to='venue.venuemodel')),
            ],
            options={
                'db_table': 'travel_logistics',
                'unique_together': {('venue', 'step_type')},
            },
        ),
    ]
