# Generated by Django 5.2.10 on 2026-03-03 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_logistics', '0001_initial'),
        ('venue', '0010_rename_venuetag_venuetagmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='travellogisticsmodel',
            name='currency',
            field=models.CharField(choices=[('UAH', 'Hryvnia'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='UAH', max_length=3),
        ),
        migrations.CreateModel(
            name='ExtraServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('hotel', 'Hotel Stay'), ('insurance', 'Insurance'), ('decoration', 'Decoration')], max_length=50)),
                ('price_type', models.CharField(choices=[('fixed', 'Fixed price'), ('per_day', 'Per day')], default='fixed', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('UAH', 'Hryvnia'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='UAH', max_length=3)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_services', to='venue.venuemodel')),
            ],
            options={
                'db_table': 'extra_services',
                'unique_together': {('venue', 'service_type')},
            },
        ),
    ]
