# Generated by Django 5.2.10 on 2026-03-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_logistics', '0002_travellogisticsmodel_currency_extraservicemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraservicemodel',
            name='currency',
            field=models.CharField(choices=[('UAH', 'Hryvnia'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='UAH', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='travellogisticsmodel',
            name='currency',
            field=models.CharField(choices=[('UAH', 'Hryvnia'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='UAH', editable=False, max_length=3),
        ),
    ]
