# Generated by Django 5.2.10 on 2026-03-07 15:00

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('travel_logistics', '0003_alter_extraservicemodel_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraServiceModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=50)),
                ('price_type', models.CharField(max_length=20, default='FIXED')),
                ('price', models.DecimalField(max_digits=10, decimal_places=2)),
                ('currency', models.CharField(max_length=3, default='UAH', editable=False)),
                ('venue', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='venue.VenueModel',
                    related_name='extra_services',
                )),
            ],
            options={
                'db_table': 'extra_services_create',
            },
        ),
    ]