# Generated by Django 5.2.10 on 2026-03-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_logistics', '0004_alter_extraservicemodel_table'),
        ('venue', '0012_delete_tablebookingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraservicemodel',
            name='currency',
            field=models.CharField(choices=[('UAH', 'Hryvnia'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='UAH', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='extraservicemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='extraservicemodel',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fixed price'), ('per_day', 'Per day')], default='fixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='extraservicemodel',
            name='service_type',
            field=models.CharField(choices=[('hotel', 'Hotel Stay'), ('insurance', 'Insurance'), ('decoration', 'Decoration')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='extraservicemodel',
            unique_together={('venue', 'service_type')},
        ),
    ]
