# Generated by Django 5.2.10 on 2026-04-12 13:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_logistics', '0005_alter_extraservicemodel_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraservicemodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), message='Price cannot be negative.')]),
        ),
        migrations.AlterField(
            model_name='travellogisticsmodel',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), message='Price cannot be negative.')]),
        ),
    ]
